config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: 'problems#index'
    get :login, to: 'sessions#new'
    post :login, to: 'sessions#create'
    delete :logout, to: 'sessions#destroy'
    resources :problems do
      collection do
        get :template
        post :upload
        get :search
      end
    end

    resources :papers, except: [:edit, :update] do
      collection do
        get :dash
        get :search
      end

      member do
        get :duplicate
        patch :terminate

        get :users, to:  'users#index'
        get :export, to: 'users#export'
        post :ranking

        post :repush
      end
    end

    get :tags, to: 'tags#index'

    resources :organizations, only: [:index] do
      member do
        get :children
      end
    end

    scope '/ranking', as: 'ranking' do
      root to: 'ranking#dash'

      scope '/individual', as: 'individual' do
        root to: 'ranking#individual'
        get :export, to: 'ranking#export_individual'
        post :push, to: 'ranking#push_individual'
      end

      scope '/company', as: 'company' do
        root to: 'ranking#company'
        get :export, to: 'ranking#export_company'
        post :push, to: 'ranking#push_company'
      end
    end
  end

  namespace :users do
    root to: 'users#dash'

    resources :papers, only: [:index, :show] do
      collection do
        get '/:code/new', as: 'new', to: 'papers#new'
        get '/:code/organizations', as: 'organizations', to: 'papers#organizations'
        post '/:code', as: 'submit', to: 'papers#create'
        get :search
      end

      member do
        get '/detail', to: 'papers#detail'
        get '/ranking', to: 'papers#ranking'
      end
    end

    resources :organizations, only: [:new, :create]

    scope '/ranking', as: 'ranking' do
      get :individual, to: 'ranking#individual'
      get :company, to: 'ranking#company'
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'
end

app/models/paper.rb
class Paper < ApplicationRecord
  has_many :enrolls
  has_many :users, through: :enrolls
  has_many :assigns
  has_many :problems, through: :assigns
  attr_accessor :problems_list
  attr_accessor :orgs_list
  accepts_nested_attributes_for :problems

  validates :code, uniqueness: true
  validates :deadline, :title, presence: true
  validates_each :deadline do |record, attr, value|
    if value < Time.now
      record.errors.add attr, "截止日期必须晚于当前时间"
    end
  end

  before_validation :generate_code
  after_save :add_problems

  default_scope { where(trashed: false) }

  def trash
    update_column :trashed, true
  end

  def terminate
    update_column :deadline, Time.now
  end

  def rank_for(score)
    Paper.count_by_sql("select array_position((select ARRAY(select score from enrolls where paper_id='#{self.id}' order by score desc nulls last)), '#{score}')")
  end

  def repush
    paper = dup

    total_score = assigns.sum(:problem_score)
    failed_user_ids = enrolls.where('score < ?', total_score * 0.6).pluck(:user_id)
    paper.user_ids = failed_user_ids

    paper.save

    assigns_params = assigns.map do |assign|
      assign.attributes.slice("problem_id", "problem_score").merge("paper_id" => paper.id)
    end

    Assign.import assigns_params

    #PublishPaperJob.perform_later paper
  end

  def self.search(q)
    Paper.where('title like ?', "%#{q}%")
  end

  private

  def generate_code
    begin
      self.code = SecureRandom.urlsafe_base64
    end while self.class.exists?(code: self.code)
  end

  def add_problems
    unless problems_list.nil?
      assigns_params = []

      problems_list.split(';').each do |id_score|
        problem_id, score = id_score.split('-')
        assigns_params.push paper_id: self.id, problem_id: problem_id, problem_score: score
      end

      Assign.import assigns_params
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :enrolls, dependent: :destroy
  has_many :papers, through: :enrolls
  has_and_belongs_to_many :organizations
  belongs_to :company, class_name: 'Organization', optional: true

  validates :uid, presence: true, uniqueness: true
  validates :name, presence: true

  def self.order_by_score_for(period)
    start_time, end_time = case period
                           when :week
                             [Time.now.at_beginning_of_week, Time.now.at_end_of_week]
                           when :month
                             [Time.now.at_beginning_of_month, Time.now.at_end_of_month]
                           when :quarter
                             [Time.now.at_beginning_of_quarter, Time.now.at_end_of_quarter]
                           end

    User.joins(:enrolls).group('users.id')
      .order("SUM(CASE WHEN enrolls.created_at > '#{start_time.to_s(:db)}' AND enrolls.created_at < '#{end_time.to_s(:db)}' THEN enrolls.score ELSE 0 END) DESC NULLS LAST")
  end

  def remember_token
    [id, Digest::SHA512.hexdigest(uid)].join('$')
  end

  def self.find_by_remember_token(token)
    user = find_by_id(token.split('$').first)
    (user && Rack::Utils.secure_compare(user.remember_token, token)) ? user : nil
  end

  def admin?
    CONFIG['admin_accounts']&.include?(uid)
  end

  def self.find_and_auth_admin(uid, password)
    if CONFIG['admin_accounts'][uid]&.fetch('password', nil) == password
      user = User.where(uid: uid).first

      if user
        user
      else
        User.create(uid: uid, name: uid, admin: true)
      end
    else
      nil
    end
  end

  def self.from_omniauth(auth_hash)
    find_or_create_by(uid: auth_hash[:uid]) do |user|
      user.name = auth_hash[:info][:name]
      user.openid = auth_hash[:info][:openid]
    end
  end

  def hand_in(paper, assigs_attributes)
    enroll = enrolls.find_by!(paper: paper)
    score, chosen_list = Assign.score_for(assigs_attributes)
    enroll.update(score: score, chosen_list: chosen_list, hand_in_time: Time.now)
  end
end

app/controllers/admin/papers_controller.rb
class Admin::PapersController < Admin::ApplicationController
  before_action :find_paper, only: [:show, :duplicate, :destroy, :terminate, :ranking, :repush]
  before_action only: [:index, :show, :search] { set_nav(:past_papers, true) }
  before_action only: [:dash, :new, :duplicate] { set_nav(:new_paper, true) }

  def dash
    @problems = Problem.untrashed.includes(:options, :tags).order(id: :desc).page(params[:page])
  end

  def index
    @papers = Paper.order(id: :desc).page(params[:page]).per(9)

    if params[:scale]
      if params[:scale] == '1'
        @papers = @papers.where(scale: 1)
      else
        @papers = @papers.where(scale: 2)
      end
    elsif params[:status]
      if params[:status] == '0'
        @papers = @papers.where('deadline > ?', Time.now)
      else
        @papers = @papers.where('deadline < ?', Time.now)
      end
    end
  end

  def show
    @problems = Problem.includes(:options, :tags).with_score(@paper.id)
  end

  def new
    @paper = Paper.new

    if params[:method] == 'random'
      single_problems = Problem.untrashed.single.includes(:options, :tags).order('random()').limit(params[:single].to_i)
      multi_problems = Problem.untrashed.multi.includes(:options, :tags).order('random()').limit(params[:multi].to_i)
      problems_by_tags = Problem.includes(:options, :tags).random_by_tags(params[:tags_list])
      @problems = single_problems + multi_problems + problems_by_tags
      render 'randomly_new'
    elsif params[:method] == 'manually'
      @problems, @remote = filter_problems
      if @remote
        render 'manually_new', layout: false
      else
        render 'manually_new'
      end
    end
  end

  def create
    @paper = Paper.new(paper_params.merge(deadline: Time.parse(paper_params[:deadline])))
    if @paper.save
      PublishPaperJob.perform_later @paper, paper_params[:orgs_list]
      redirect_to admin_paper_url @paper
    else
      render body: nil
    end
  end

  def duplicate
    @problems = Problem.includes(:options, :tags).with_score(@paper.id)
    @paper = @paper.dup
    render 'randomly_new'
  end

  def repush
    @paper.repush
  end

  def terminate
    @paper.terminate
    redirect_to admin_paper_url(@paper)
  end

  def destroy
    @paper.trash
    redirect_to admin_papers_url
  end

  def search
    @papers = Paper.search(params[:q].to_s).order(id: :desc).page(params[:page]).per(9)
    respond_to do |format|
      format.html { render :index }
      format.json do
        @papers = @papers.page(1).per(5)
        render json: @papers.to_json(only: :title)
      end
    end
  end

  def ranking
    PushRankJob.perform_later @paper
  end

  def orgs
    @orgs = SkylarkAdapter.get_orgs

    respond_to do |format|
      format.json do
        render json: @orgs.to_json(only: [:id, :name])
      end
    end
  end

  private

  def paper_params
    params.require(:paper).permit(:title, :scale, :problems_list, :deadline, :orgs_list)
  end

  def find_paper
    @paper = Paper.find(params[:id])
  end
end

app/controllers/admin/users_controller.rb
require 'csv'

class Admin::UsersController < Admin::ApplicationController
  before_action only: [:index] { set_nav(:past_papers, true) }

  def index
    @paper = Paper.find(params[:id])
    @enrolls = @paper.enrolls.includes(user: [:organizations]).order('users.id ASC').page(params[:page])

    if params[:q]
      @enrolls = @enrolls.search(params[:q].to_s)
    end

    if params[:status]
      if params[:status] == '0'
        @enrolls = @enrolls.finished
      else
        @enrolls = @enrolls.unfinished
      end
    elsif params[:rank]
      if params[:rank] == '0'
        @enrolls = @enrolls.finished.reorder(score: :asc)
      else
        @enrolls = @enrolls.finished.reorder(score: :desc)
      end
    elsif params[:failed]
      total = @paper.assigns.sum(:problem_score)
      @enrolls = @enrolls.finished.where('score < ?', total * 0.6)
    end
  end

  def export
    paper = Paper.find(params[:id])
    send_data(Exporter::ExcelExporter.export_paper_ranking(paper), type: 'application/xlsx', filename: "#{Time.now.to_i}.xlsx")
  end
end

app/controllers/users/application_controller.rb
class Users::ApplicationController < ApplicationController
  layout 'users'

  before_action :login_required, :select_company_required

  def select_company_required
    unless @current_user.company
      redirect_to new_users_organization_url(return_to: (request.fullpath if request.get?))
    end
  end

  def login_url(params)
    store_location params[:return_to]
    '/auth/skylark'
  end
end

app/controllers/users/organizations_controller.rb
class Users::OrganizationsController < Users::ApplicationController
  skip_before_action :select_company_required

  def new
    store_location params[:return_to]
    @organizations = @current_user.organizations.leaf.distinct

    redirect_back_or_default(users_papers_url) if @organizations.count == 0
  end

  def create
    @current_user.company = Organization.find params[:company]
    @current_user.save
    redirect_back_or_default users_papers_url
  end
end

app/controllers/users/papers_controller.rb
class Users::PapersController < Users::ApplicationController
  layout 'users'

  before_action :filter_papers, only: [:index]
  before_action :find_paper, only: [:show, :detail, :ranking]
  before_action :find_paper_by_code, only: [:new, :create]
  before_action :detect_paper_availability, only: [:new, :create]

  def new
    if !@available && current_user.paper_ids.include?(@paper.id)
      redirect_to users_paper_url(@paper)
    end

    @assigns = Assign.includes(problem: [:options]).joins(:paper).where(paper: @paper)
  end

  def organizations
  end

  def create
    if @available
      current_user.hand_in(@paper, paper_params[:assigns_attributes])
      redirect_to users_paper_url(@paper)
    else
      render :hand_in_error
    end
  end

  def index
  end

  def show
    @enroll = current_user.enrolls.find_by!(paper: @paper)
    @rank = @paper.rank_for(@enroll.score) unless @enroll.hand_in_time.nil?
  end

  def detail
    @available = false
    @detailed = true
    @enroll = current_user.enrolls.finished.find_by!(paper: params[:id])
    @assigns = Assign.includes(problem: [:options]).joins(:paper).where(paper: @paper)
    render :new
  end

  def ranking
    @enrolls = @paper.enrolls.order('score DESC NULLS LAST')
  end

  def search
    @papers = current_user.papers.search(params[:q].to_s).distinct.order(created_at: :desc)
    render :index
  end

  private

  def filter_papers
    @papers = current_user.papers.distinct.order(created_at: :desc)

    if params[:scale]
      @papers = @papers.where(scale: params[:scale])
    elsif params[:running]
      if params[:running] == '0'
        @papers = @papers.where('deadline < ?', Time.now)
      else
        @papers = @papers.where('deadline > ?', Time.now)
      end
    elsif params[:finished]
      if params[:finished] == '0'
        @papers = @papers.joins(:enrolls).where(enrolls: { hand_in_time: nil })
      else
        @papers = @papers.joins(:enrolls).where.not(enrolls: { hand_in_time: nil })
      end
    end
  end

  def detect_paper_availability
    @available = false
    enroll = current_user.enrolls.find_by(paper: @paper)

    if enroll
      unless enroll.hand_in_time
        if Time.now < @paper.deadline
          @available = true
        end
      end
    end
  end

  def find_paper
    @paper = current_user.papers.find(params[:id])
  end

  def find_paper_by_code
    @paper = Paper.find_by!(code: params[:code])
  end

  def paper_params
    params.require(:paper).permit(assigns_attributes: [:chosen])
  end
end

app/controllers/users/ranking_controller.rb
class Users::RankingController < Users::ApplicationController
  def individual
    @users = User.includes(:organizations).order_by_score_for(params[:period].to_sym)
  end

  def company
    @organizations = Organization.order_by_score_for(params[:period].to_sym)
  end
end

app/controllers/users/users_controller.rb
class Users::UsersController < Users::ApplicationController
  layout 'users'

  def dash
  end
end

app/helpers/admin/papers_helper.rb
module Admin::PapersHelper
  def display_time(time)
    time.localtime.strftime("%Y年%m月%d日 %H:%M") unless time.nil?
  end

  def num_of_failed(paper)
    total = paper.assigns.sum(:problem_score)
    paper.enrolls.where('score < ?', total * 0.6).count
  end

  def other_params_field
    if params[:status]
      hidden_field_tag :status, params[:status]
    elsif params[:rank]
      hidden_field_tag :rank, params[:rank]
    elsif params[:failed]
      hidden_field_tag :failed, params[:failed]
    end
  end

  def rank_of(i)
    if params[:page]
      i + 1 + 20 * (params[:page].to_i - 1)
    else
      i + 1
    end
  end
end

app/helpers/users/papers_helper.rb
module Users::PapersHelper
  def finished?(paper)
    !!@current_user.enrolls.find_by(paper: paper).hand_in_time
  end

  def failed?(enroll)
    enroll.score < enroll.paper.assigns.sum(:problem_score) * 0.6
  end

  def done_wrong?(chosen_list, problem_id)
    !chosen_list.detect do |chosen|
      problem_id_t, chosen_option_ids = chosen.split('-')

      (problem_id_t.to_i == problem_id) && (Problem.find(problem_id).right?(chosen_option_ids))
    end
  end

  def chosen?(chosen_list, problem_id, option_id)
    !!chosen_list.detect do |chosen|
      problem_id_t, chosen_option_ids = chosen.split('-')

      (problem_id_t.to_i == problem_id) && (!!chosen_option_ids&.split(';')&.detect { |chosen_option_id| chosen_option_id.to_i == option_id })
    end
  end
end

app/views/users/papers/_assign.html.erb
<% problem = assign.problem %>
<% if @detailed && done_wrong %>
  <div class="paper-questions-cell problem-cell" style="background-color: #f7bebe;">
<% else %>
  <div class="paper-questions-cell problem-cell">
<% end %>
  <div class="cell-description">
    <span><%= i + 1 %>.</span>
    <span class="cell-title">
      <%= problem.description %>
    </span>
    <span class="cell-type">
      <span>(</span><span class="cell-type-text">
        <%= problem.form == 1 ? '单选' : '多选' %>
      </span><span>)</span>
    </span>
    <span class="cell-score">
      <%= assign.problem_score %>
    </span>
    <span>分</span>
  </div>
  <div class="cell-options">
    <ol type="A">
      <% problem.options.each do |option| %>
        <li class="option" data-id=<%= option.id %>>
          <div class="form-check">
            <label class="custom-control custom-checkbox">
              <% if @detailed && chosen?(chosen_list, problem.id, option.id) %>
                <input type="checkbox" class="custom-control-input" checked>
              <% else %>
                <input type="checkbox" class="custom-control-input">
              <% end %>
              <span class="custom-control-indicator <%= problem.form ==1 ? 'single-check' : '' %>"></span>
              <span class="custom-control-description">
                <%= option.description %>
              </span>
            </label>
            <% if @detailed && done_wrong && option.right? %>
              <i class="fa fa-check"></i>
            <% end %>
          </div>
        </li>
      <% end %>
    </ol>
  </div>
  <% if available %>
    <%= hidden_field_tag "paper[assigns_attributes][#{assign.id}][chosen]","",class: "selected-options-input" %>
  <% end %>
</div>

app/views/users/papers/index.html.erb
<div class="all-papers-container">
  <div class="papers-search">
    <%= form_tag search_users_papers_url, method: :get, class: "form-inline" do %>
      <i class="fa fa-search"></i>
      <%= text_field_tag :q, params[:q], class: "form-control mr-sm-2", placeholder: "搜索" %>
    <% end %>
  </div>
  <div class="prev-papers">
    <span>往期考试</span>
    <span class="show-filter"><i class="fa fa-bars"></i></span>
    <div class="filter-list">
      <div class="filter-top">
        <span class="return-icon"><i class="fa fa-arrow-left"></i></span>
        <span>筛选</span>
      </div>
      <div class="filter-middle">
        <%= link_to "小考", users_papers_url(scale: 1), class: 'filter-cell' %>
        <%= link_to "进行中", users_papers_url(running: 1), class: 'filter-cell' %>
        <%= link_to "未参与", users_papers_url(finished: 0), class: 'filter-cell' %>
        <%= link_to "大考", users_papers_url(scale: 2), class: 'filter-cell' %>
        <%= link_to "已关闭", users_papers_url(running: 0), class: 'filter-cell' %>
        <%= link_to "已完成", users_papers_url(finished: 1), class: 'filter-cell' %>
      </div>
      <div class="filter-bottom">
        <%= link_to "重置", users_papers_url %>
      </div>
    </div>
  </div>
  <% @papers.each do |paper| %>
    <% finished = finished?(paper) %>
    <% if finished %>
      <div class="paper-cell" data-id="<%= paper.id %>">
    <% else %>
      <div class="paper-cell" data-code="<%= paper.code %>">
    <% end %>
      <div class="cell-top">
        <div class="cell-paper-title">
          <span class="title-text">
            <%= paper.title %>
          </span>
          <span class="test-type running">
            <%= paper.scale == 1 ? '小考' : '大考' %>
          </span>
        </div>
        <div class="cell-paper-information">
          <span>发布者：</span>
          <span>渠道小助手</span>
        </div>
        <div class="cell-paper-information">
          <span>题目数：</span>
          <span>
            <%= paper.assigns.count %>
          </span>
        </div>
        <div class="cell-paper-information">
          <span>总分：</span>
          <span>
            <%= paper.assigns.sum(:problem_score) %>
          </span>
        </div>
        <div class="cell-paper-information">
          <span>试卷关闭时间：</span>
          <span>
            <%= display_time(paper.deadline) %>
          </span>
        </div>
      </div>
      <div class="cell-bottom">
        <% over = Time.now > paper.deadline %>
        <span class="<%= over ? 'closed' : 'running' %>">
          <%= over ? '已结束' : '进行中' %>
        </span>
        <span class="<%= finished ? 'running' : 'closed' %>">
          <%= finished ? '已完成' : '未参与' %>
        </span>
      </div>
    </div>
  <% end %>
</div>

app/views/users/papers/new.html.erb
<div class="users-papers-container">
  <div class="users-papers-header">
    <div class="header-left">
      <div class="users-papers-title">
        <%= @paper.title %>
      </div>
      <div class="papers-information">
        <div class="information-cell">
          <span>发布者：</span>
          <span>渠道小助手</span>
        </div>
        <div class="information-cell">
          <span>考试类型：</span>
          <span>
            <%= @paper.scale == 1 ? '小考' : '大考' %>
          </span>
        </div>
        <div class="information-cell">
          <span>题目数：</span>
          <span>
            <%= @paper.problems.count %>
          </span>
        </div>
        <div class="information-cell">
          <span>总分：</span>
          <span>
            <%= @paper.assigns.sum(:problem_score) %>
          </span>
        </div>
        <div class="information-cell">
          <span>试卷关闭时间：</span>
          <span>
            <%= display_time(@paper.deadline) %>
          </span>
        </div>
      </div>
    </div>
    <div class="header-right">
      <span class="head-icon"><i class="fa fa-file-text-o"></i></span>
      <% over = Time.now > @paper.deadline %>
      <span class="papers-status <%= over ? 'closed' : 'running' %>">
        <%= over ? '已关闭' : '进行中' %>
      </span>
    </div>
  </div>
  <% if @available %>
    <%= form_for @paper, url: submit_users_papers_url(@paper.code),html: { id: "submit_paper" }, method: "post" do |f| %>
      <div class="users-papers-body">
        <% @assigns.each_with_index do |assign, i| %>
          <%= render partial: 'assign', locals: { available: @available, assign: assign, i: i } %>
        <% end %>
      </div>
      <div class="users-papers-divider"></div>
      <div class="users-papers-footer">
        <a class="btn btn-danger" id="submit-paper-button">
          <i class="fa fa-check-square-o"></i>
          <span>提交</span>
        </a>
      </div>
    <% end %>
  <% else %>
    <div class="users-papers-body" style="margin-bottom: 0px;">
      <% @assigns.each_with_index do |assign, i| %>
        <%= render partial: 'assign', locals: { available: @available, assign: assign, done_wrong: done_wrong?(@enroll.chosen_list, assign.problem.id), chosen_list: @enroll.chosen_list,
                                                i: i } %>
      <% end %>
    </div>
  <% end %>
  <% if @detailed %>
    <div class="users-papers-footer">
      <a class="btn btn-danger" href="<%= users_paper_url(@paper) %>">
        <i class="fa fa-repeat"></i>
        <span>返回成绩</span>
      </a>
    </div>
  <% end %>
</div>

app/views/users/papers/ranking.html.erb
<div class="users-papers-container">
  <div class="users-papers-header">
    <div class="header-left">
      <div class="users-papers-title">
        <%= @paper.title %>
      </div>
      <div class="papers-information">
        <div class="information-cell">
          <span>发布者：</span>
          <span>渠道小助手</span>
        </div>
        <div class="information-cell">
          <span>考试类型：</span>
          <span>
            <%= @paper.scale == 1 ? '小考' : '大考' %>
          </span>
        </div>
        <div class="information-cell">
          <span>题目数：</span>
          <span>
            <%= @paper.problems.count %>
          </span>
        </div>
        <div class="information-cell">
          <span>总分：</span>
          <span>
            <%= @paper.assigns.sum(:problem_score) %>
          </span>
        </div>
        <div class="information-cell">
          <span>试卷关闭时间：</span>
          <span>
            <%= display_time(@paper.deadline) %>
          </span>
        </div>
      </div>
    </div>
    <div class="header-right">
      <span class="head-icon">
        <i class="fa fa-check-square-o running "></i>
      </span>
      <span class="papers-status running">已完成</span>
    </div>
  </div>
  <div class="users-papers-header" style="display: none;">
    <div class="header-left">
      <div class="users-papers-title">
        个人周排名
      </div>
      <div class="papers-information">
        <div class="information-cell">
          <span>排名类型：</span>
          <span>
            111
          </span>
        </div>
        <div class="information-cell">
          <span>参考人数：</span>
          <span>
            111
          </span>
        </div>
        <div class="information-cell">
          <span>总分：</span>
          <span>
            111
          </span>
        </div>
        <div class="information-cell">
          <span>时间：</span>
          <span>
            111
          </span>
        </div>
      </div>
    </div>
    <div class="header-right">
      <span class="head-icon cchl-icon">
      </span>
    </div>
  </div>
  <div class="ranking-list">
    <table class="table table-hover table-bordered table-striped ranking-table">
      <thead>
        <tr class="tr">
          <td>排名</td>
          <td>姓名</td>
          <td>得分</td>
          <td>公司</td>
        </tr>
      </thead>
      <tbody id="listdata">
        <% @enrolls.each_with_index do |enroll, i| %>
          <% user = enroll.user %>
          <tr class="tr">
            <td><%= rank_of(i) %></td>
            <td><%= user.name %></td>
            <td><%= enroll.score %></td>
            <td><%= user.organizations.first.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="users-papers-footer">
    <a class="btn btn-danger" href="<%= users_paper_url(@paper) %>"
      <i class="fa fa-undo"></i>
      <span>返回成绩</span>
    </a>
    <div class="papers-search" style="display: none;">
      <form class="form-inline">
        <i class="fa fa-search"></i>
        <input class="form-control mr-sm-2" type="text" placeholder="搜索姓名" aria-label="Search">
      </form>
    </div>
  </div>
</div>

app/views/users/papers/show.html.erb
<div class="users-papers-container">
  <div class="users-papers-header">
    <div class="header-left">
      <div class="users-papers-title">
        <%= @paper.title %>
      </div>
      <div class="papers-information">
        <div class="information-cell">
          <span>发布者：</span>
          <span>渠道小助手</span>
        </div>
        <div class="information-cell">
          <span>考试类型：</span>
          <span>
            <%= @paper.scale == 1 ? '小考' : '大考' %>
          </span>
        </div>
        <div class="information-cell">
          <span>题目数：</span>
          <span>
            <%= @paper.problems.count %>
          </span>
        </div>
        <div class="information-cell">
          <span>总分：</span>
          <span>
            <%= @paper.assigns.sum(:problem_score) %>
          </span>
        </div>
        <div class="information-cell">
          <span>试卷关闭时间：</span>
          <span>
            <%= display_time(@paper.deadline) %>
          </span>
        </div>
      </div>
    </div>
    <div class="header-right">
      <% finished = finished?(@paper) %>
      <span class="head-icon">
        <i class="fa <%= finished ? 'fa-check-square-o running' : 'fa-file-text-o' %>"></i>
      </span>
      <span class="papers-status running">
        <% if finished %>
          已完成
        <% else %>
          进行中
        <% end %>
      </span>
    </div>
  </div>
  <% if finished %>
    <div class="score-list">
      <div class="score-list-title">
        <span>得分</span>
      </div>
      <div class="score-text">
        <% if @paper.scale == 1 %>
          <span class="score-number running">
            <%= @enroll.score %>
          </span>
        <% else %>
          <% failed = failed?(@enroll) %>
          <span class="score-number <%= failed ? 'closed' : 'running' %>">
            <%= @enroll.score %>
          </span>
          <span class="unqualified <%= failed ? 'closed' : 'running' %>">
            <%= failed ? '不合格' : '合格' %>
          </span>
        <% end %>
      </div>
    </div>
    <div class="individual-ranking">
      <span>排名</span>
      <span class="ranking-number"><%= @rank %></span>
      <%= link_to '查看本次考试排名', ranking_users_paper_url(@paper), class: 'btn' %>
      <span class="ranking-explain">
        排名为实时显示,最终排名以试卷关闭后为准
      </span>
    </div>
    <div class="users-papers-button-group">
      <%= link_to "返回试卷", detail_users_paper_url(@paper), class: 'btn return' %>
      <%= link_to "往期试卷", users_papers_url, class: 'btn show-allpapers' %>
    </div>
  <% end %>
</div>