config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: 'problems#index'
    get :login, to: 'sessions#new'
    post :login, to: 'sessions#create'
    delete :logout, to: 'sessions#destroy'
    resources :problems do
      collection do
        get :template
        post :upload
        get :search
      end
    end

    resources :papers, except: [:edit, :update] do
      collection do
        get :dash
        get :search
      end

      member do
        get :duplicate
        patch :terminate

        get :users, to:  'users#index'
        get :export, to: 'users#export'
        post :ranking

        post :repush
      end
    end

    get :tags, to: 'tags#index'

    resources :organizations, only: [:index] do
      member do
        get :children
      end
    end

    scope '/ranking', as: 'ranking' do
      root to: 'ranking#dash'

      scope '/individual', as: 'individual' do
        root to: 'ranking#individual'
        get :export, to: 'ranking#export_individual'
        post :push, to: 'ranking#push_individual'
      end

      scope '/company', as: 'company' do
        root to: 'ranking#company'
        get :export, to: 'ranking#export_company'
        post :push, to: 'ranking#push_company'
      end
    end
  end

  namespace :users do
    root to: 'users#dash'

    resources :papers, only: [:index, :show] do
      collection do
        get '/:code/new', as: 'new', to: 'papers#new'
        get '/:code/organizations', as: 'organizations', to: 'papers#organizations'
        post '/:code', as: 'submit', to: 'papers#create'
        get :search
      end

      member do
        get '/detail', to: 'papers#detail'
        get '/ranking', to: 'papers#ranking'
      end
    end

    resources :organizations, only: [:new, :create]

    scope '/ranking', as: 'ranking' do
      get :individual, to: 'ranking#individual'
      get :company, to: 'ranking#company'
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'
end

app/models/paper.rb
class Paper < ApplicationRecord
  has_many :enrolls
  has_many :users, through: :enrolls
  has_many :assigns
  has_many :problems, through: :assigns
  attr_accessor :problems_list
  attr_accessor :orgs_list
  accepts_nested_attributes_for :problems

  validates :code, uniqueness: true
  validates :deadline, :title, presence: true
  validates_each :deadline do |record, attr, value|
    if value < Time.now
      record.errors.add attr, "截止日期必须晚于当前时间"
    end
  end

  before_validation :generate_code
  after_save :add_problems

  default_scope { where(trashed: false) }

  def trash
    update_column :trashed, true
  end

  def terminate
    update_column :deadline, Time.now
  end

  def rank_for(score)
    Paper.count_by_sql("select array_position((select ARRAY(select score from enrolls where paper_id='#{self.id}' order by score desc nulls last)), '#{score}')")
  end

  def repush
    paper = dup

    total_score = assigns.sum(:problem_score)
    failed_user_ids = enrolls.where('score < ?', total_score * 0.6).pluck(:user_id)
    paper.user_ids = failed_user_ids

    paper.save

    assigns_params = assigns.map do |assign|
      assign.attributes.slice("problem_id", "problem_score").merge("paper_id" => paper.id)
    end

    Assign.import assigns_params

    #PublishPaperJob.perform_later paper
  end

  def self.search(q)
    Paper.where('title like ?', "%#{q}%")
  end

  private

  def generate_code
    begin
      self.code = SecureRandom.urlsafe_base64
    end while self.class.exists?(code: self.code)
  end

  def add_problems
    unless problems_list.nil?
      assigns_params = []

      problems_list.split(';').each do |id_score|
        problem_id, score = id_score.split('-')
        assigns_params.push paper_id: self.id, problem_id: problem_id, problem_score: score
      end

      Assign.import assigns_params
    end
  end
end

app/controllers/admin/papers_controller.rb
class Admin::PapersController < Admin::ApplicationController
  before_action :find_paper, only: [:show, :duplicate, :destroy, :terminate, :ranking, :repush]
  before_action only: [:index, :show, :search] { set_nav(:past_papers, true) }
  before_action only: [:dash, :new, :duplicate] { set_nav(:new_paper, true) }

  def dash
    @problems = Problem.untrashed.includes(:options, :tags).order(id: :desc).page(params[:page])
  end

  def index
    @papers = Paper.order(id: :desc).page(params[:page]).per(9)

    if params[:scale]
      if params[:scale] == '1'
        @papers = @papers.where(scale: 1)
      else
        @papers = @papers.where(scale: 2)
      end
    elsif params[:status]
      if params[:status] == '0'
        @papers = @papers.where('deadline > ?', Time.now)
      else
        @papers = @papers.where('deadline < ?', Time.now)
      end
    end
  end

  def show
    @problems = Problem.includes(:options, :tags).with_score(@paper.id)
  end

  def new
    @paper = Paper.new

    if params[:method] == 'random'
      single_problems = Problem.untrashed.single.includes(:options, :tags).order('random()').limit(params[:single].to_i)
      multi_problems = Problem.untrashed.multi.includes(:options, :tags).order('random()').limit(params[:multi].to_i)
      problems_by_tags = Problem.includes(:options, :tags).random_by_tags(params[:tags_list])
      @problems = single_problems + multi_problems + problems_by_tags
      render 'randomly_new'
    elsif params[:method] == 'manually'
      @problems, @remote = filter_problems
      if @remote
        render 'manually_new', layout: false
      else
        render 'manually_new'
      end
    end
  end

  def create
    @paper = Paper.new(paper_params.merge(deadline: Time.parse(paper_params[:deadline])))
    if @paper.save
      PublishPaperJob.perform_later @paper, paper_params[:orgs_list]
      redirect_to admin_paper_url @paper
    else
      render body: nil
    end
  end

  def duplicate
    @problems = Problem.includes(:options, :tags).with_score(@paper.id)
    @paper = @paper.dup
    render 'randomly_new'
  end

  def repush
    @paper.repush
  end

  def terminate
    @paper.terminate
    redirect_to admin_paper_url(@paper)
  end

  def destroy
    @paper.trash
    redirect_to admin_papers_url
  end

  def search
    @papers = Paper.search(params[:q].to_s).order(id: :desc).page(params[:page]).per(9)
    respond_to do |format|
      format.html { render :index }
      format.json do
        @papers = @papers.page(1).per(5)
        render json: @papers.to_json(only: :title)
      end
    end
  end

  def ranking
    PushRankJob.perform_later @paper
  end

  def orgs
    @orgs = SkylarkAdapter.get_orgs

    respond_to do |format|
      format.json do
        render json: @orgs.to_json(only: [:id, :name])
      end
    end
  end

  private

  def paper_params
    params.require(:paper).permit(:title, :scale, :problems_list, :deadline, :orgs_list)
  end

  def find_paper
    @paper = Paper.find(params[:id])
  end
end

app/controllers/users/papers_controller.rb
class Users::PapersController < Users::ApplicationController
  layout 'users'

  before_action :filter_papers, only: [:index]
  before_action :find_paper, only: [:show, :detail, :ranking]
  before_action :find_paper_by_code, only: [:new, :create]
  before_action :detect_paper_availability, only: [:new, :create]

  def new
    if !@available && current_user.paper_ids.include?(@paper.id)
      redirect_to users_paper_url(@paper)
    end

    @assigns = Assign.includes(problem: [:options]).joins(:paper).where(paper: @paper)
  end

  def organizations
  end

  def create
    if @available
      current_user.hand_in(@paper, paper_params[:assigns_attributes])
      redirect_to users_paper_url(@paper)
    else
      render :hand_in_error
    end
  end

  def index
  end

  def show
    @enroll = current_user.enrolls.find_by!(paper: @paper)
    @rank = @paper.rank_for(@enroll.score) unless @enroll.hand_in_time.nil?
  end

  def detail
    @available = false
    @detailed = true
    @enroll = current_user.enrolls.finished.find_by!(paper: params[:id])
    @assigns = Assign.includes(problem: [:options]).joins(:paper).where(paper: @paper)
    render :new
  end

  def ranking
    @enrolls = @paper.enrolls.order('score DESC NULLS LAST')
  end

  def search
    @papers = current_user.papers.search(params[:q].to_s).distinct.order(created_at: :desc)
    render :index
  end

  private

  def filter_papers
    @papers = current_user.papers.distinct.order(created_at: :desc)

    if params[:scale]
      @papers = @papers.where(scale: params[:scale])
    elsif params[:running]
      if params[:running] == '0'
        @papers = @papers.where('deadline < ?', Time.now)
      else
        @papers = @papers.where('deadline > ?', Time.now)
      end
    elsif params[:finished]
      if params[:finished] == '0'
        @papers = @papers.joins(:enrolls).where(enrolls: { hand_in_time: nil })
      else
        @papers = @papers.joins(:enrolls).where.not(enrolls: { hand_in_time: nil })
      end
    end
  end

  def detect_paper_availability
    @available = false
    enroll = current_user.enrolls.find_by(paper: @paper)

    if enroll
      unless enroll.hand_in_time
        if Time.now < @paper.deadline
          @available = true
        end
      end
    end
  end

  def find_paper
    @paper = current_user.papers.find(params[:id])
  end

  def find_paper_by_code
    @paper = Paper.find_by!(code: params[:code])
  end

  def paper_params
    params.require(:paper).permit(assigns_attributes: [:chosen])
  end
end

app/helpers/admin/papers_helper.rb
module Admin::PapersHelper
  def display_time(time)
    time.localtime.strftime("%Y年%m月%d日 %H:%M") unless time.nil?
  end

  def num_of_failed(paper)
    total = paper.assigns.sum(:problem_score)
    paper.enrolls.where('score < ?', total * 0.6).count
  end

  def other_params_field
    if params[:status]
      hidden_field_tag :status, params[:status]
    elsif params[:rank]
      hidden_field_tag :rank, params[:rank]
    elsif params[:failed]
      hidden_field_tag :failed, params[:failed]
    end
  end

  def rank_of(i)
    if params[:page]
      i + 1 + 20 * (params[:page].to_i - 1)
    else
      i + 1
    end
  end
end

app/helpers/users/papers_helper.rb
module Users::PapersHelper
  def finished?(paper)
    !!@current_user.enrolls.find_by(paper: paper).hand_in_time
  end

  def failed?(enroll)
    enroll.score < enroll.paper.assigns.sum(:problem_score) * 0.6
  end

  def done_wrong?(chosen_list, problem_id)
    !chosen_list.detect do |chosen|
      problem_id_t, chosen_option_ids = chosen.split('-')

      (problem_id_t.to_i == problem_id) && (Problem.find(problem_id).right?(chosen_option_ids))
    end
  end

  def chosen?(chosen_list, problem_id, option_id)
    !!chosen_list.detect do |chosen|
      problem_id_t, chosen_option_ids = chosen.split('-')

      (problem_id_t.to_i == problem_id) && (!!chosen_option_ids&.split(';')&.detect { |chosen_option_id| chosen_option_id.to_i == option_id })
    end
  end
end

app/views/admin/papers/dash.html.erb
<h3 class="page-header">发布考试</h3>
<div class="set-prob">
  <div class="set-prob-top">出题方式</div>
  <div class="set-prob-content">
    <button class="btn btn-randomly btn-main" data-toggle="modal" data-target="#randomModal">随机出题</button>
    <a class="btn btn-manually" id="manully_new" href="/admin/papers/new?method=manually">手动出题</a>
  </div>
</div>

<% @template_options = { navbar: [], navbar_title: "题库", options: true, actions: [:edit, :show] } %>
<%= render partial: "shared/problems", object: @problems %>

<div class="modal fade random-questions-modal" id="randomModal" tabindex="-1" role="dialog" aria-labelledby="randomModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
     <div class="modal-content">
       <div class="modal-header">
         <div class="modal-title-wrapper">
          <h5 class="modal-title" id="randomModalLabel">随机出题</h5>
         </div>
         <button type="button" class="close" data-dismiss="modal" aria-label="Close">
           <span aria-hidden="true">&times;</span>
         </button>
       </div>
       <form class="modal-body-wrapper">
         <div class="modal-body">
           <div class="questions-type">
             <div class="questions-type-radio">
               <span>单选</span>
               <input class="number-input form-control" id="single_choice" onkeyup="this.value=this.value.replace(/\D/g,'')" onafterpaste="this.value=this.value.replace(/\D/g,'')" >
               <span>题</span>
             </div>
             <div class="questions-type-checkbox">
               <span>多选</span>
               <input class="number-input form-control" id="multi_choice" onkeyup="this.value=this.value.replace(/\D/g,'')" onafterpaste="this.value=this.value.replace(/\D/g,'')" >
               <span>题</span>
             </div>
           </div>
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
            <button type="button" class="btn btn-main random-button">确认</button>
         </div> 
       </form>
     </div>
  </div>
</div>

app/views/admin/papers/index.html.erb
<h3 class="page-header">往期考试</h3>
<div class="papers-list-wrapper">
  <div class="navbar-wrapper">
    <nav class="navbar navbar-light">
      <%= form_tag search_admin_papers_path, method: :get, class: "form-inline", id: "submit-search" do %>
        <i class="fa fa-search search"></i>
        <%= text_field_tag :q, params[:q], class: "form-control mr-sm-2", id: "search-input", autocomplete: "off" %>
        <ul id="autosearch"></ul>
      <% end %>
    </nav>
    <div class="navbar-right">
      <select class="custom-select mb-2 mr-sm-2 mb-sm-0 select-test">
        <option value="3">全部</option>
        <option value="1">小考</option>
        <option value="2">大考</option>
        <option selected="" style="display: none;">考试类型</option>
      </select>
      <select class="custom-select mb-2 mr-sm-2 mb-sm-0 select-status">
        <option value="2">全部</option>
        <option value="0">进行中</option>
        <option value="1">已结束</option>
        <option selected="" style="display: none;">试卷状态</option>
      </select>
    </div>
  </div>
  <div class="papers-container">
    <div class="card-wrapper">
      <% @papers.each do |paper| %>
        <div class="card-cell papers-card paper-item" data-id=<%= paper.id %>>
          <% over = Time.now > paper.deadline %>
          <div class="card-top">
            <div class="card-title">
              <div class="title-wrapper">
                <span class="title-text"><%= paper.title %></span>
                <span class="title-test-type <%= over ? 'closed' : 'running' %>"><%= paper.scale == 1 ? "小考" : "大考" %></span>
              </div>
              <div class="paper-status <%= over ? 'closed' : 'running' %>">
                <%= over ? '已结束' : '进行中' %>
              </div>
            </div>
            <div class="paper-deadline">
              <span class="deadline"><%= display_time paper.deadline %></span>
              <span>截止</span>
            </div>
          </div>
          <div class="card-bottom">
            <div class="card-bottom-left">
              <div class="examinees-number">
                <span>参考人数：</span>
                <span class="examinees-number-text">
                  <%= paper.enrolls.count %>
                </span>
              </div>
              <div class="finished-number">
                <span>已完成人数：</span>
                <span class="finished-number-text">
                  <%= paper.enrolls.where.not(hand_in_time: nil).count %>
                </span>
              </div>
              <div class="unfinished-number">
                <span>未完成人数：</span>
                <span class="unfinished-number-text">
                  <%= paper.enrolls.where(hand_in_time: nil).count %>
                </span>
              </div>
            </div>
            <% if paper.scale ==  2 %>
              <div class="card-bottom-right">
                <div class="unqualified">
                  <span>不合格人数：</span>
                  <span class="unqualified-number">
                    <%= num_of_failed(paper) %>
                  </span>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="pagination-wrapper">
  <%= paginate @papers %>
</div>

app/views/admin/papers/manually_new.html.erb
<h3 class="page-header">手动出题</h3>
<div class="set-prob set-papers">
  <div class="set-prob-top">试卷设置</div>
  <div class="set-papers-content">
    <%= form_for ([:admin, @paper]), html: { class: "paper_form" } do |f| %>
      <div class="papers-type">
        <span>考试类型：</span>
        <label class="custom-control custom-radio">
          <%= f.radio_button :scale, 1, class: "custom-control-input small-test", checked: true %>
          <span class="custom-control-indicator"></span>
          <span class="custom-control-description">小考</span>
        </label>
        <label class="custom-control custom-radio">
          <%= f.radio_button :scale, 2, class: "custom-control-input large-test" %>
          <span class="custom-control-indicator"></span>
          <span class="custom-control-description">大考</span>
        </label>
      </div>
      <div class="papers-information-wrapper">
        <div class="papers-information-left">
          <div class="papers-name">
            <div class="name">
              <span>试卷名称：</span>
              <%= f.text_field :title, class: "form-control papers-name-val" %>
            </div>
          </div>
          <div class="papers-user">
            <span>考生选择：</span>
            <div class="user-range" tabindex="0" hidefocus="true">
              <span class="user-overflow-text" style="display: none;">等组织...</span>
              <span class="dropdown-icon"><i class="fa fa-chevron-down"></i></span>
            </div>
            <div id="select-organizations"></div>
          </div>
        </div>
        <div class="papers-information-right">
          <div class="qualified-score">
            <div class="score" style="display: none;">
              <span>合格分数：</span>
              <input type="text" class="form-control papers-score-val" placeholder="如未填写，合格分数为总分的60%" onkeyup="value=value.replace(/[^\d\.]/g,'')">
            </div>
          </div>
          <div class="papers-closetime">
            <span>试卷关闭时间：</span>
            <input type="text" id="datetimepicker" class="form-control" name="paper[deadline]" readonly data-date-format="yyyy-mm-dd hh:ii">
            <span class="dropdown-icon"><i class="fa fa-chevron-down"></i></span>
          </div>
        </div>
      </div>
      <%= f.hidden_field :problems_list, id: "problems_list" %>
      <%= f.hidden_field :orgs_list, id: "orgs_list" %>
    <% end %>
  </div>
</div>


<div class="manually-new">
  <div class="manually-problems-wrapper flex-percentage">
    <% @template_options = { wrapper_class: "manually-problems",
                             navbar: [:search], navbar_title: "题库", actions: [:show, :edit, :add] } %>
    <%= render partial: "shared/problems", object: @problems %>
  </div>

  <div class="manually-papers-wrapper flex-percentage">
    <div class="manually-papers-content">
      <% @template_options = { wrapper_class: "manually-papers", scores: true, nopager: true,
                               navbar: [:create], navbar_title: "试卷", actions: [:remove] } %>
      <%= render partial: "shared/problems", object: [] %>
      <div class="papers-pagination-wrapper">
        <nav style="display: none;">
          <ul class="pagination">
            <li class="page-item first-page">
              <a class="page-link">
              首页</a>
            </li>
            <li class="page-item previous">
              <a class="page-link"><i class="fa fa-arrow-left"></i></a>
            </li>
            <li class="page-item next">
              <a class="page-link"><i class="fa fa-arrow-right"></i></a>
            </li>
            <li class="page-item last-page">
              <a class="page-link">
              尾页</a>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>
<div class="release-test">
  <button class="btn btn-primary releaseButton" data-toggle="modal" data-target="#releaseModal">发布考试</button>
</div>
<div class="modal fade release-modal" id="releaseModal" tabindex="-1" role="dialog" aria-labelledby="releaseModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
     <div class="modal-content">
       <div class="modal-header">
         <div class="modal-title-wrapper">
          <h5 class="modal-title" id="releaseModalLabel">确认发布</h5>
         </div>
         <button type="button" class="close" data-dismiss="modal" aria-label="Close">
           <span aria-hidden="true">&times;</span>
         </button>
       </div>
       <form class="modal-body-wrapper">
         <div class="modal-body">
           <div class="modal-body-content">
             <div class="papers-name cell">
               <span>试卷名称：</span>
               <span class="name-content"></span>
             </div>
             <div class="papers-type cell">
               <span>考试类型：</span>
               <span class="type-content"></span>
             </div>
             <div class="user cell">
               <span>考生：</span>
               <span class="user-range-content"></span>
               <span class="overflow-text" style="display: none;">等组织...</span>
             </div>
             <div class="prob-number cell">
               <span>题目数：</span>
               <span class="prob-number-content"></span>
             </div>
             <div class="papers-totalscore cell">
               <span>试卷总分：</span>
               <span class="total-scores"></span>
             </div>
             <div class="papers-closetime cell">
               <span>试卷关闭时间：</span>
               <span class="papers-close-time"></span>
             </div>
           </div>
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-primary" id="publish_paper">确认发布</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
         </div>
       </form>
     </div>
  </div>
</div>

app/views/admin/papers/show.html.erb
<% over = Time.now > @paper.deadline %>

<div class="paper-title">
  <a href="/admin/papers" class="return">往期考试</a>
  <span>\</span>
  <span class="title-text"><%= @paper.title %></span>
</div>
<div class="paper-information">
  <h2 class="paper-name"><%= @paper.title %></h2>
  <div class="wrapper">
    <div class="paper-status <%= over ? 'closed' : 'running' %>"><%= over ? '已结束' : '进行中' %></div>
    <div class="paper-deadline"><%= display_time @paper.deadline %></div>
  </div>
</div>
<div class="papers-list-wrapper">
  <div class="navbar-wrapper paper-show-navbar">
    <nav class="navbar navbar-light">    
    </nav>
    <div class="navbar-right">
      <% unless over %>
        <button class="btn close-examination" data-toggle="modal" data-target="#terminateModal">
          <span>结束考试</span>
          <i class="fa fa-times"></i>
        </button>
      <% end %>
      <a class="btn copy-paper" href="<%= duplicate_admin_paper_url(@paper) %>">
        <span>复制考卷</span>
        <i class="fa fa-clipboard"></i>
      </a>
      <button class="btn dele-paper" data-toggle="modal" data-target="#deleteModal">
        <span>删除考卷</span>
        <i class="fa fa-trash-o"></i>
      </button>
    </div>
  </div>
  <div class="papers-container">
    <div class="card-wrapper">
      <div class="card-cell papers-card">
        <div class="card-top">
          <div class="card-title">
            <div class="title-wrapper">
              <span class="title-text"><%= @paper.title %></span>
              <span class="title-test-type <%= over ? 'closed' : 'running' %>"><%= @paper.scale == 1 ? '小考' : '大考' %></span>
            </div>
            <div class="paper-status"></div>
          </div>
        </div>
        <div class="card-bottom">
          <div class="card-bottom-left">
            <div class="questions-number">
              <span>题目数：</span>
              <span class="questions-number-text"><%= @problems.length %></span>
            </div>
            <div class="paper-total-score">
              <span>总分：</span>
              <span class="paper-total-score-text"><%= @paper.assigns.sum(:problem_score) %></span>
            </div>
            <div class="examinees-number">
              <span>参考人数：</span>
              <span class="examinees-number-text">
                <%= @paper.enrolls.count %>
              </span>
            </div>
            <div>
              <span>试卷关闭时间：</span>
              <span class="deadline"><%= display_time @paper.deadline %></span>
            </div>
          </div>
        </div>
      </div>
      <div class="card-cell papers-card users-information finished">
        <div class="card-top">
          <div class="card-title">
            <div class="title-wrapper">
              <span class="title-text">已完成人数</span>
            </div>
          </div>
        </div>
        <div class="card-bottom-information">
          <span class="information-icon"><i class="fa fa-users"></i></span>
          <span class="information-text finished-number">
            <%= @paper.enrolls.where.not(hand_in_time: nil).count %>
          </span>
        </div>
      </div>
      <div class="card-cell papers-card users-information unfinished">
        <div class="card-top">
          <div class="card-title">
            <div class="title-wrapper">
              <span class="title-text">未完成人数</span>
            </div>
          </div>
        </div>
        <div class="card-bottom-information">
          <span class="information-icon"><i class="fa fa-user"></i></span>
          <span class="information-text unfinished-number">
            <%= @paper.enrolls.where(hand_in_time: nil).count %>
          </span>
        </div>
      </div>
      <% if @paper.scale == 2 %>
        <div class="card-cell papers-card users-information failed">
          <div class="card-top">
            <div class="card-title">
              <div class="title-wrapper">
                <span class="title-text">不合格名单</span>
              </div>
            </div>
          </div>
          <div class="card-bottom-information">
            <span class="information-icon"><i class="fa fa-times"></i></span>
            <span class="information-text finish-number">
              <%= num_of_failed(@paper) %>
            </span>
          </div>
        </div>
      <% end %>
      <div class="card-cell papers-card users-information rank">
        <div class="card-top">
          <div class="card-title">
            <div class="title-wrapper">
              <span class="title-text"></span>
            </div>
          </div>
        </div>
        <div class="card-bottom-information">
          <span class="information-icon"><i class="fa fa-bar-chart"></i></span>
          <span class="information-text finish-number">得分排名</span>
        </div>
      </div>
    </div>
  </div>
</div>
<% @template_options = { navbar: [], navbar_title: "全部题目", nopager: true, scores: true, options: true, actions: [:show] } %>
<%= render partial: "shared/problems", object: @problems %>
<div class="return-papers-list">
  <a href="/admin/papers" class="btn btn-primary">返回</a>
</div>
<div class="modal fade dele-modal" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
     <div class="modal-content">
       <div class="modal-header">
         <div class="modal-title-wrapper">
          <h5 class="modal-title" id="deleteModalLabel">确认删除</h5>
         </div>
         <button type="button" class="close" data-dismiss="modal" aria-label="Close">
           <span aria-hidden="true">&times;</span>
         </button>
       </div>
       <div class="modal-body">
         <span class="body-text">试卷删除后无法恢复，是否确认删除？</span>
       </div>
       <div class="modal-footer">
         <div class="footer-btn">
           <%= link_to '确认删除', admin_paper_url(@paper), class: "btn btn-danger btn-dele", method: :delete %>
           <button class="btn btn-secondary btn-cancel" data-dismiss="modal">取消</button>
         </div>
       </div>
     </div>
  </div>
</div>
<div class="modal fade dele-modal" id="terminateModal" tabindex="-1" role="dialog" aria-labelledby="terminateModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
     <div class="modal-content">
       <div class="modal-header">
         <div class="modal-title-wrapper">
          <h5 class="modal-title" id="terminateModalLabel">确认结束</h5>
         </div>
         <button type="button" class="close" data-dismiss="modal" aria-label="Close">
           <span aria-hidden="true">&times;</span>
         </button>
       </div>
       <div class="modal-body">
         <span class="body-text">考试结束后无法恢复，是否确认结束？</span>
       </div>
       <div class="modal-footer">
         <div class="footer-btn">
           <%= link_to '确认结束', terminate_admin_paper_url(@paper), class: "btn btn-danger btn-dele", method: :patch %>
           <button class="btn btn-secondary btn-cancel" data-dismiss="modal">取消</button>
         </div>
       </div>
     </div>
  </div>
</div>