config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: 'problems#index'
    get :login, to: 'sessions#new'
    post :login, to: 'sessions#create'
    delete :logout, to: 'sessions#destroy'
    resources :problems do
      collection do
        get :template
        post :upload
        get :search
      end
    end

    resources :papers, except: [:edit, :update] do
      collection do
        get :dash
        get :search
      end

      member do
        get :duplicate
        patch :terminate

        get :users, to:  'users#index'
        get :export, to: 'users#export'
        post :ranking

        post :repush
      end
    end

    get :tags, to: 'tags#index'

    resources :organizations, only: [:index] do
      member do
        get :children
      end
    end

    scope '/ranking', as: 'ranking' do
      root to: 'ranking#dash'

      scope '/individual', as: 'individual' do
        root to: 'ranking#individual'
        get :export, to: 'ranking#export_individual'
        post :push, to: 'ranking#push_individual'
      end

      scope '/company', as: 'company' do
        root to: 'ranking#company'
        get :export, to: 'ranking#export_company'
        post :push, to: 'ranking#push_company'
      end
    end
  end

  namespace :users do
    root to: 'users#dash'

    resources :papers, only: [:index, :show] do
      collection do
        get '/:code/new', as: 'new', to: 'papers#new'
        get '/:code/organizations', as: 'organizations', to: 'papers#organizations'
        post '/:code', as: 'submit', to: 'papers#create'
        get :search
      end

      member do
        get '/detail', to: 'papers#detail'
        get '/ranking', to: 'papers#ranking'
      end
    end

    resources :organizations, only: [:new, :create]

    scope '/ranking', as: 'ranking' do
      get :individual, to: 'ranking#individual'
      get :company, to: 'ranking#company'
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :enrolls, dependent: :destroy
  has_many :papers, through: :enrolls
  has_and_belongs_to_many :organizations
  belongs_to :company, class_name: 'Organization', optional: true

  validates :uid, presence: true, uniqueness: true
  validates :name, presence: true

  def self.order_by_score_for(period)
    start_time, end_time = case period
                           when :week
                             [Time.now.at_beginning_of_week, Time.now.at_end_of_week]
                           when :month
                             [Time.now.at_beginning_of_month, Time.now.at_end_of_month]
                           when :quarter
                             [Time.now.at_beginning_of_quarter, Time.now.at_end_of_quarter]
                           end

    User.joins(:enrolls).group('users.id')
      .order("SUM(CASE WHEN enrolls.created_at > '#{start_time.to_s(:db)}' AND enrolls.created_at < '#{end_time.to_s(:db)}' THEN enrolls.score ELSE 0 END) DESC NULLS LAST")
  end

  def remember_token
    [id, Digest::SHA512.hexdigest(uid)].join('$')
  end

  def self.find_by_remember_token(token)
    user = find_by_id(token.split('$').first)
    (user && Rack::Utils.secure_compare(user.remember_token, token)) ? user : nil
  end

  def admin?
    CONFIG['admin_accounts']&.include?(uid)
  end

  def self.find_and_auth_admin(uid, password)
    if CONFIG['admin_accounts'][uid]&.fetch('password', nil) == password
      user = User.where(uid: uid).first

      if user
        user
      else
        User.create(uid: uid, name: uid, admin: true)
      end
    else
      nil
    end
  end

  def self.from_omniauth(auth_hash)
    find_or_create_by(uid: auth_hash[:uid]) do |user|
      user.name = auth_hash[:info][:name]
      user.openid = auth_hash[:info][:openid]
    end
  end

  def hand_in(paper, assigs_attributes)
    enroll = enrolls.find_by!(paper: paper)
    score, chosen_list = Assign.score_for(assigs_attributes)
    enroll.update(score: score, chosen_list: chosen_list, hand_in_time: Time.now)
  end
end

app/controllers/admin/users_controller.rb
require 'csv'

class Admin::UsersController < Admin::ApplicationController
  before_action only: [:index] { set_nav(:past_papers, true) }

  def index
    @paper = Paper.find(params[:id])
    @enrolls = @paper.enrolls.includes(user: [:organizations]).order('users.id ASC').page(params[:page])

    if params[:q]
      @enrolls = @enrolls.search(params[:q].to_s)
    end

    if params[:status]
      if params[:status] == '0'
        @enrolls = @enrolls.finished
      else
        @enrolls = @enrolls.unfinished
      end
    elsif params[:rank]
      if params[:rank] == '0'
        @enrolls = @enrolls.finished.reorder(score: :asc)
      else
        @enrolls = @enrolls.finished.reorder(score: :desc)
      end
    elsif params[:failed]
      total = @paper.assigns.sum(:problem_score)
      @enrolls = @enrolls.finished.where('score < ?', total * 0.6)
    end
  end

  def export
    paper = Paper.find(params[:id])
    send_data(Exporter::ExcelExporter.export_paper_ranking(paper), type: 'application/xlsx', filename: "#{Time.now.to_i}.xlsx")
  end
end

app/controllers/users/application_controller.rb
class Users::ApplicationController < ApplicationController
  layout 'users'

  before_action :login_required, :select_company_required

  def select_company_required
    unless @current_user.company
      redirect_to new_users_organization_url(return_to: (request.fullpath if request.get?))
    end
  end

  def login_url(params)
    store_location params[:return_to]
    '/auth/skylark'
  end
end

app/controllers/users/organizations_controller.rb
class Users::OrganizationsController < Users::ApplicationController
  skip_before_action :select_company_required

  def new
    store_location params[:return_to]
    @organizations = @current_user.organizations.leaf.distinct

    redirect_back_or_default(users_papers_url) if @organizations.count == 0
  end

  def create
    @current_user.company = Organization.find params[:company]
    @current_user.save
    redirect_back_or_default users_papers_url
  end
end

app/controllers/users/papers_controller.rb
class Users::PapersController < Users::ApplicationController
  layout 'users'

  before_action :filter_papers, only: [:index]
  before_action :find_paper, only: [:show, :detail, :ranking]
  before_action :find_paper_by_code, only: [:new, :create]
  before_action :detect_paper_availability, only: [:new, :create]

  def new
    if !@available && current_user.paper_ids.include?(@paper.id)
      redirect_to users_paper_url(@paper)
    end

    @assigns = Assign.includes(problem: [:options]).joins(:paper).where(paper: @paper)
  end

  def organizations
  end

  def create
    if @available
      current_user.hand_in(@paper, paper_params[:assigns_attributes])
      redirect_to users_paper_url(@paper)
    else
      render :hand_in_error
    end
  end

  def index
  end

  def show
    @enroll = current_user.enrolls.find_by!(paper: @paper)
    @rank = @paper.rank_for(@enroll.score) unless @enroll.hand_in_time.nil?
  end

  def detail
    @available = false
    @detailed = true
    @enroll = current_user.enrolls.finished.find_by!(paper: params[:id])
    @assigns = Assign.includes(problem: [:options]).joins(:paper).where(paper: @paper)
    render :new
  end

  def ranking
    @enrolls = @paper.enrolls.order('score DESC NULLS LAST')
  end

  def search
    @papers = current_user.papers.search(params[:q].to_s).distinct.order(created_at: :desc)
    render :index
  end

  private

  def filter_papers
    @papers = current_user.papers.distinct.order(created_at: :desc)

    if params[:scale]
      @papers = @papers.where(scale: params[:scale])
    elsif params[:running]
      if params[:running] == '0'
        @papers = @papers.where('deadline < ?', Time.now)
      else
        @papers = @papers.where('deadline > ?', Time.now)
      end
    elsif params[:finished]
      if params[:finished] == '0'
        @papers = @papers.joins(:enrolls).where(enrolls: { hand_in_time: nil })
      else
        @papers = @papers.joins(:enrolls).where.not(enrolls: { hand_in_time: nil })
      end
    end
  end

  def detect_paper_availability
    @available = false
    enroll = current_user.enrolls.find_by(paper: @paper)

    if enroll
      unless enroll.hand_in_time
        if Time.now < @paper.deadline
          @available = true
        end
      end
    end
  end

  def find_paper
    @paper = current_user.papers.find(params[:id])
  end

  def find_paper_by_code
    @paper = Paper.find_by!(code: params[:code])
  end

  def paper_params
    params.require(:paper).permit(assigns_attributes: [:chosen])
  end
end

app/controllers/users/ranking_controller.rb
class Users::RankingController < Users::ApplicationController
  def individual
    @users = User.includes(:organizations).order_by_score_for(params[:period].to_sym)
  end

  def company
    @organizations = Organization.order_by_score_for(params[:period].to_sym)
  end
end

app/controllers/users/users_controller.rb
class Users::UsersController < Users::ApplicationController
  layout 'users'

  def dash
  end
end

app/helpers/users/papers_helper.rb
module Users::PapersHelper
  def finished?(paper)
    !!@current_user.enrolls.find_by(paper: paper).hand_in_time
  end

  def failed?(enroll)
    enroll.score < enroll.paper.assigns.sum(:problem_score) * 0.6
  end

  def done_wrong?(chosen_list, problem_id)
    !chosen_list.detect do |chosen|
      problem_id_t, chosen_option_ids = chosen.split('-')

      (problem_id_t.to_i == problem_id) && (Problem.find(problem_id).right?(chosen_option_ids))
    end
  end

  def chosen?(chosen_list, problem_id, option_id)
    !!chosen_list.detect do |chosen|
      problem_id_t, chosen_option_ids = chosen.split('-')

      (problem_id_t.to_i == problem_id) && (!!chosen_option_ids&.split(';')&.detect { |chosen_option_id| chosen_option_id.to_i == option_id })
    end
  end
end

app/views/admin/users/_users.html.erb
<div class="papers-list-wrapper">
  <div class="navbar-wrapper">
    <nav class="navbar navbar-light">
      <%= form_tag users_admin_paper_url(@paper), method: :get, class: "form-inline",id: "submit-search" do %>
        <i class="fa fa-search search"></i>
        <%= text_field_tag :q, params[:q], class: "form-control mr-sm-2", id: "search-input", autocomplete: "off" %>
        <%= other_params_field %>
      <% end %>
    </nav>
    <div class="navbar-right">
      <% if params[:rank] %>
        <%= link_to "下载导出得分排名", export_admin_paper_url(params[:id]), class: "btn btn-info download-list", data: { turbolinks: false } %>
      <% end %>
      <%= link_to "将成绩与排名推送给用户", ranking_admin_paper_url, method: :post, class: "btn btn-success push-score" %>
      <% if @paper.scale == 2 && params[:failed] %>
        <%= link_to "对不合格人员推送再次考试", repush_admin_paper_url(params[:id]), method: :post, class: "btn btn-info download-list", data: { turbolinks: false } %>
      <% end %>
    </div>
  </div>
  <div class="container-wrapper">
    <div class="container name-list-container">
      <table class="table table-hover table-bordered table-striped index-table">
        <thead>
          <tr class="tr">
            <% if params[:rank] %>
              <td>排名</td>
            <% end %>
            <td>姓名</td>
            <td>公司名称</td>
            <td>得分</td>
            <td>完成时间</td>
          </tr>
        </thead>
        <tbody id="listdata">
          <% @enrolls.each_with_index do |enroll, i| %>
            <tr class="tr">
              <% if params[:rank] %>
                <td>
                  <%= rank_of(i) %>
                </td>
              <% end %>
              <td><%= enroll.user.name %></td>
              <td><%= enroll.user.organizations.first.name %></td>
              <td class="score"><%= enroll.score %></td>
              <td><%= display_time(enroll.hand_in_time) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="pagination-wrapper">
      <%= paginate @enrolls %>
    </div>
  </div>
</div>
<div class="return-papers-list">
  <a class="btn btn-primary" onclick="javascript:history.back(-1)">返回</a>
</div>

app/views/admin/users/index.html.erb
<div class="paper-users-header">
  <h3 class="information-title"><%= @paper.title %></h3>
  <h3 class="users-list">
    <% if params[:status] == "0" %>
      已完成名单
    <% elsif params[:status] == "1" %>
      未完成名单
    <% elsif params[:failed] == "1" %>
      不合格名单
    <% else %>
      得分排名
    <% end %>
  </h3>
</div>

<%= render partial: "users" %>